<?php

namespace Cypress\DiDebuggerBundle\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class DiDebugCommand
 * @package Cypress\DiDebuggerBundle\Command
 */
class DiDebugCommand extends Command
{
    protected function configure()
    {
        $this->setName('cypress:di:debug');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
