language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - hhvm

branches:
  only:
    - master

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev install

script:
  - bin/phpspec run

  
